# Generated by Django 3.2 on 2022-03-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpkuser',
            name='rules',
        ),
    ]
